version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: academypro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      #DATABASE_URL: postgresql+asyncpg://postgres.nlzyqywkjwcilqymbmzz:uOf4oWp3g0SqlqaG@aws-1-eu-north-1.pooler.supabase.com:5432/postgres
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/academypro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  pgdata:
